### PR TITLE
Update IE613-iHBADeltas.conf

### PR DESCRIPTION
**Pull request by David-McKenna**
This allows for the correct UVW coordinates to be determined in SEPTON-style observations, such as all-sky imaging. This PR updates the IE613-iHBADeltas.conf to the newer version provided by Menno Norden.

### CODE REVIEW

**Comment by 2baOrNot2ba** [comment]
Thanks for spotting these old iHBADeltas. Do you have an example of *IE613* SEPTON data that I could test this on?

**Comment by David-McKenna** [comment]
http://86.47.107.67:443/data/xst-SEPTON/

Those were taken last Tuesday while Joe and I were debugged issues, I
haven't yet re-processed them with iLiSA since we discovered the outdated
iHBADeltas, but it should be fine.

Processing them on my laptop with my scripts (iLiSA runs out of memory)
generates the plots below from frame 2 for the YY correlations (I is
extremely similar but has less intensity around the Milky Way which is very
quiet in the X polarisation). Left is old iHBADeltas, right is new
iHBADeltas. Both use the IE613 caltables.

https://i.imgur.com/XSakVec.png

**Comment by 2baOrNot2ba** [comment]
Thanks David, I can confirm that I got good images too with this data (using iLiSA). You mention iLiSA running out of memory on you laptop. Could you mention a bit more detail on that to find out if there is anything I can do. (I can't reproduce "out of memory" on my laptop with iLiSA)

**Comment by David-McKenna** [comment]
It's likely a side effect of my laptop having only 4gb of ram, been causing
me random issues for quite a while now. Just running image.py caused the
process to be 'Killed' or python raising 'OutOfMemoryError' after a few
seconds. Not much else to say about it.

**Pull request merged**
